# Generated by Django 2.0.2 on 2018-03-06 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('G_designer', models.CharField(max_length=64, null=True)),
                ('G_developer', models.CharField(max_length=64, null=True)),
                ('T_manager1', models.CharField(max_length=64, null=True)),
                ('T_manager2', models.CharField(max_length=64, null=True)),
                ('remarks', models.CharField(max_length=64, null=True)),
                ('U_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JustPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_name', models.CharField(max_length=64, unique=True)),
                ('P_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagement.Project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='D_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagement.Task', to_field='T_name'),
        ),
        migrations.AddField(
            model_name='detail',
            name='T_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagement.JustPlan'),
        ),
    ]
